<?php
/**
 * Plugin Name: WebP Express
 * Plugin URI: https://github.com/rosell-dk/webp-express
 * Description: Serve autogenerated WebP images instead of jpeg/png to browsers that supports WebP. Works on anything (media library images, galleries, theme images etc).
 * Version: 0.11.1
 * Author: Bjørn Rosell
 * Author URI: https://www.bitwise-it.dk
 * License: GPL2
 */

/*
Note: Perhaps create a plugin page on my website?, ie https://www.bitwise-it.dk/software/wordpress/webp-express
*/

define('WEBPEXPRESS_PLUGIN', __FILE__);
define('WEBPEXPRESS_PLUGIN_DIR', __DIR__);

if (is_admin()) {
    include __DIR__ . '/lib/admin.php';
}

//add_action( 'wp_ajax_foobar', 'my_ajax_foobar_handler' );


function webp_express_process_post() {
    // strip query string
    $requestUriNoQS = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);

    if (!preg_match('/webp-express-web-service$/', $requestUriNoQS)) {
        return;
    }
    //include __DIR__ . '/lib/wpc.php';
    include __DIR__ . '/web-service/wpc.php';
    die();
}
add_action( 'init', 'webp_express_process_post' );

if (get_option('webp-express-alter-html', false)) {
    require_once __DIR__ . '/lib/classes/AlterHtmlInit.php';
    \WebPExpress\AlterHtmlInit::setHooks();
}

/*
function webpexpress_addWebPJs() {
    $url = plugins_url('webpjs/webpjs-0.0.2.min.js', __FILE__);
    $script = <<<EOD
<script>
    (function(){
        var WebP=new Image();
        WebP.onload=WebP.onerror=function(){
            if(WebP.height!=2){
                var sc=document.createElement('script');
                sc.type='text/javascript';
                sc.async=true;
                var s=document.getElementsByTagName('script')[0];
                sc.src='$url';
                s.parentNode.insertBefore(sc,s);
            }
        };
        WebP.src='data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA';
    })();
</script>
EOD;
    echo $script;
}

add_action( 'wp_head', 'webpexpress_addWebPJs');
*/
//add_action( 'template_redirect', 'webp_express_template_redirect' );
